apiVersion: v1
kind: Pod
metadata:
  labels:
    app: iperf3-server
    role: iperf3-server
  name: iperf3-server
  namespace: iperf-test
  annotations:
    "cni.projectcalico.org/vpp.memif.ports":  "tcp:4444-20000,udp:4444-20000"
    "cni.projectcalico.org/vpp.tuntap.ports": "default"
spec:
  containers:
  - name: iperf3
    image: clearlinux/iperf:3
    command: ['/bin/sh', '-c', 'sleep 1d']
    ports:
    - containerPort: 5201
