apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3
  namespace: iperf-test
  labels:
    app: iperf3-client
    role: iperf3-client
  annotations:
    "cni.projectcalico.org/vpp.memif.ports":  "tcp:4444-20000,udp:4444-20000"
    "cni.projectcalico.org/vpp.tuntap.ports": "default"
spec:
  selector:
    matchLabels:
      app: iperf3-client
  template:
    metadata:
      labels:
        app: iperf3-client
    spec:
      containers:
      - name: iperf3
        image: clearlinux/iperf:3
        command: ['/bin/sh', '-c', 'sleep 1d']
        ports:
        - containerPort: 5201
